apiVersion: v1
kind: Service
metadata:
  name: opcua-datalogger-service
  namespace: default
  labels:
    app: opcua-datalogger
spec:
  ports:
    - name: socket
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: misc
      protocol: TCP
      port: 4444
      targetPort: 4444
  selector:
    app: opcua-datalogger
    id: "asdasd"
  type: ClusterIP
