apiVersion: doteich.com/v1alpha1
kind: LoggerConfig
metadata:
  name: test
  namespace: default
spec:
  data: |
    {
    "opcConfig": {
        "url": "opc.tcp://IPorURL",
        "securityPolicy": "None",
        "securityMode": "None",
        "authType": "User & Password",
        "username": "*",
        "password": "*",
        "node": "ns=3;s=NODE"
    },
    "selectedTags": [{
        "nodeId": "ns=3;s=XYZ",
        "name": "TESTTAG1"
    }],
    "methodConfig": {
        "subInterval": 10,
        "name": "TestLogger",
        "description": null
    }
    }
