apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: gopclogs-controller
spec:
  parentResource:
    apiVersion: doteich.com/v1alpha1
    resource: loggerconfigs
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: RollingRecreate
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: RollingRecreate
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: RollingRecreate
  generateSelector: true
  hooks:
    sync:
      webhook:
        url: http://gopclogs-operator.metacontroller/sync
        timeout: 60s