apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: opcua-datalogger-pod-monitor
  namespace: default
  labels:
    app: opcua-datalogger
    resource: opcua-datalogger-monitoring-pm
spec:
  selector:
    matchLabels:
      app: opcua-datalogger
  podMetricsEndpoints:
  - targetPort: 4444
    path: /metrics
    interval: 30s